/* ============================================================
   blog-data.js — All 10 Optiiimum personal-branding articles.
   Used by blog-post.html (?slug=…) and the Home/Blog listings.
   Content is bilingual (en + ar) and structured as block arrays
   so the template renders headings, lists, and pull-quotes
   semantically. Update copy here, not inside HTML.
   ============================================================ */
window.BLOG_POSTS = [
  {
    slug: "what-is-personal-branding",
    cover: "assets/blogs/01_what-is-personal-branding.jpg",
    titleEn: "What is personal branding?",
    titleAr: "ما هو البراند الشخصي؟",
    categoryEn: "Personal Branding · Foundations",
    categoryAr: "البراند الشخصي · الأساسيات",
    summaryEn: "A practical guide to building a professional image that doesn't get forgotten.",
    summaryAr: "دليل عملي لبناء صورة احترافية لا تُنسى.",
    readEn: "6 min read",
    body: [
      { type: "lede",
        en: "Personal branding isn't a logo, a font choice, or a Canva template. It's the answer to a single question: <strong>when your name comes up in a room you're not in, what gets said?</strong>",
        ar: "البراند الشخصي مش لوجو ولا فونت ولا تمبليت في Canva. هو الإجابة على سؤال واحد: <strong>لما اسمك يتقال في أوضة انت مش فيها، الناس بتقول إيه؟</strong>" },
      { type: "h2",
        en: "The working definition we use",
        ar: "التعريف اللي بنشتغل بيه" },
      { type: "p",
        en: "A personal brand is the consistent, public expression of a specialist position — delivered through visible work, point-of-view content, and a recognisable visual system. Three words matter: <strong>consistent</strong>, <strong>specialist</strong>, and <strong>visible</strong>. Drop any one and you have a person with opinions. Hold all three and you have a brand.",
        ar: "البراند الشخصي هو التعبير العلني والمتسق عن موقع تخصصي معين — من خلال شغل واضح، محتوى له وجهة نظر، ونظام بصري ممكن تتعرّف عليه. تلات كلمات بتفرق: <strong>متسق</strong>، <strong>متخصص</strong>، و<strong>ظاهر للعلن</strong>. لو نزّلت واحدة منهم، يبقى انت شخص له آراء. خليهم كلهم، يبقى عندك براند." },
      { type: "h2",
        en: "What it is not",
        ar: "إيه اللي مش بيكون براند شخصي" },
      { type: "ul",
        enItems: [
          "It's not your CV — your CV summarises history. Your brand sells the future.",
          "It's not your job title — a brand outlives the job.",
          "It's not influencer culture — influencers borrow attention; brands compound it.",
          "It's not a profile photo and bio rewrite — those are receipts, not the system."
        ],
        arItems: [
          "مش الـ CV بتاعك — الـ CV بيلخّص تاريخك، البراند بيبيع مستقبلك.",
          "مش المسمى الوظيفي — البراند بيكمّل بعد الوظيفة.",
          "مش ثقافة الإنفلونسرز — الإنفلونسر بياخد انتباه مؤقت، البراند بيراكم.",
          "مش بروفايل بكتر وبايو متظبط — دي إيصالات، مش هي النظام."
        ] },
      { type: "h2",
        en: "The three layers that make a brand recognisable",
        ar: "التلات طبقات اللي بتخلي البراند يتعرف عليه" },
      { type: "h3",
        en: "1) Position — the room you own",
        ar: "١) الموقع — الأوضة اللي بتمتلكها" },
      { type: "p",
        en: "Generalists die online. \"Marketing\" is a category. \"Performance media for healthcare brands\" is a position. The narrower your room, the louder your signal.",
        ar: "اللي بيشتغل في كل حاجة بيختفي على الإنترنت. \"تسويق\" دي تصنيف، أما \"إعلانات أداء للبراندات الطبية\" ده موقع. كل ما الأوضة تضيق، الصوت يعلى." },
      { type: "h3",
        en: "2) Point of view — the opinion that costs you something",
        ar: "٢) وجهة النظر — الرأي اللي بيكلّفك حاجة" },
      { type: "p",
        en: "Safe opinions don't compound. The opinions that build a brand are the ones a competitor would never say — because they cost something to hold publicly.",
        ar: "الآراء الآمنة مش بتراكم. الآراء اللي بتبني براند هي اللي منافسك مش هيقولها — لأنها بتكلّف اللي بيقولها." },
      { type: "h3",
        en: "3) Pattern — the visible cadence",
        ar: "٣) النمط — الإيقاع الظاهر" },
      { type: "p",
        en: "Every recognisable brand has a rhythm — a posting cadence, a visual signature, a recurring format. Pattern is what makes the audience expect you, even before you arrive.",
        ar: "كل براند مميز عنده إيقاع — معدّل نشر، توقيع بصري، فورمات بيتكرّر. النمط هو اللي بيخلي الجمهور يستنّاك حتى قبل ما تطلع." },
      { type: "quote",
        en: "A personal brand is the byproduct of doing a clear thing, publicly, on a clock.",
        ar: "البراند الشخصي هو ناتج إنك تعمل حاجة واضحة، أمام الناس، على إيقاع منتظم." },
      { type: "h2",
        en: "How to start in the next 30 days",
        ar: "إزاي تبدأ في الـ ٣٠ يوم الجاية" },
      { type: "ol",
        enItems: [
          "Pick the narrowest position you're qualified to hold — and live with the discomfort.",
          "Write the one opinion only you would say out loud.",
          "Choose a single format you can ship weekly for a year.",
          "Build a visual system you can apply in 90 seconds, not 90 minutes.",
          "Publish on a clock. Measure quarterly, not weekly."
        ],
        arItems: [
          "اختار أضيق موقع انت مؤهل تشغله — واستحمل الإحساس اللي معاه.",
          "اكتب الرأي الوحيد اللي بس انت اللي ممكن تقوله بصوت عالي.",
          "اختار فورمات واحد تقدر تنزّله أسبوعياً لمدة سنة.",
          "ابنِي نظام بصري تقدر تطبّقه في ٩٠ ثانية، مش ٩٠ دقيقة.",
          "انشر على إيقاع. قِيس كل ربع سنة، مش كل أسبوع."
        ] }
    ]
  },

  {
    slug: "build-personal-brand-from-scratch",
    cover: "assets/blogs/02_build-personal-brand-from-scratch.jpg",
    titleEn: "Build a strong personal brand from scratch",
    titleAr: "ابني براند شخصي قوي من الصفر",
    categoryEn: "Personal Branding · Build",
    categoryAr: "البراند الشخصي · بناء",
    summaryEn: "A step-by-step playbook to build your personal brand from zero — with clarity, consistency, and an audience-pulling edge.",
    summaryAr: "دليل عملي خطوة بخطوة لبناء براندك الشخصي من الصفر — بوضوح، باستمرار، وبطريقة بتجذب الجمهور.",
    readEn: "8 min read",
    body: [
      { type: "lede",
        en: "Most people don't start a brand. They start a feed. The difference shows up in month six — when the feed has noise, the brand has compounding.",
        ar: "أغلب الناس مش بتبني براند. بتبني فيد. الفرق بيبان في الشهر السادس — لما الفيد بيبقى ضوضاء، والبراند بيبدأ يتراكم." },
      { type: "h2",
        en: "Phase 1 · Choose a position you can defend for 24 months",
        ar: "المرحلة ١ · اختار موقع تقدر تدافع عنه ٢٤ شهر" },
      { type: "p",
        en: "Pick the position you'd still be proud of in two years, not the one that pulls fast follows this month. Defensibility = expertise × interest × supply.",
        ar: "اختار الموقع اللي لسه هتفتخر بيه بعد سنتين، مش اللي هيجيبلك متابعين سريع الشهر ده. القدرة على الدفاع = خبرة × اهتمام × ندرة." },
      { type: "h2",
        en: "Phase 2 · Build a content thesis, not a content calendar",
        ar: "المرحلة ٢ · ابني أطروحة محتوى، مش جدول محتوى" },
      { type: "p",
        en: "A calendar tells you when to post. A thesis tells you what to fight for. Your thesis is the 5-7 ideas you'll repeat in different formats for the next two years.",
        ar: "الجدول بيقولك تنشر إمتى. الأطروحة بتقولك بتحارب علشان إيه. الأطروحة هي ٥-٧ أفكار هتعيد تقديمهم بأشكال مختلفة على مدار سنتين." },
      { type: "h3",
        en: "How to find your 5 ideas",
        ar: "إزاي تلاقي الـ ٥ أفكار بتوعك" },
      { type: "ul",
        enItems: [
          "List 20 opinions you hold strongly about your field.",
          "Cross out the 15 anyone else would also say.",
          "From the remaining 5, pick the 3 you can prove with case work."
        ],
        arItems: [
          "اكتب ٢٠ رأي عندك قوي في مجالك.",
          "اشطب الـ ١٥ اللي أي حد في مجالك ممكن يقولهم.",
          "من الـ ٥ الباقيين، اختار ٣ تقدر تثبتهم بشغل فعلي."
        ] },
      { type: "h2",
        en: "Phase 3 · Visible work beats visible opinions",
        ar: "المرحلة ٣ · الشغل الظاهر بيتغلب على الآراء الظاهرة" },
      { type: "p",
        en: "Opinions get likes. Case studies get clients. From day one, document the work — not the journey. Build in public, but ship in public too.",
        ar: "الآراء بتجيب لايكات. الـ Case studies بتجيب عملاء. من اليوم الأول، وثّق الشغل — مش الرحلة. ابني قدّام الناس، بس نزّل قدّامهم برضو." },
      { type: "quote",
        en: "A brand built only on opinion is a brand built on a borrowed audience.",
        ar: "البراند المبني على آراء بس، براند مبني على جمهور مستعار." },
      { type: "h2",
        en: "Phase 4 · The 18-month patience tax",
        ar: "المرحلة ٤ · ضريبة الصبر — ١٨ شهر" },
      { type: "p",
        en: "Real personal brands don't compound in 90 days. They compound when the audience starts <em>quoting you back to you</em>. That usually happens around month 14-18. Plan for it.",
        ar: "البراند الشخصي الحقيقي مش بيراكم في ٩٠ يوم. بيراكم لما الجمهور يبدأ <em>يرجّعلك كلامك تاني</em>. وده عادةً بيحصل حوالين الشهر ١٤-١٨. خطّط على الأساس ده." }
    ]
  },

  {
    slug: "personal-brand-vs-personal-marketing",
    cover: "assets/blogs/03_personal-brand-vs-personal-marketing.jpg",
    titleEn: "Personal brand or personal marketing?",
    titleAr: "براند شخصي ولاّ تسويق شخصي؟",
    categoryEn: "Personal Branding · Foundations",
    categoryAr: "البراند الشخصي · الأساسيات",
    summaryEn: "Know the difference between personal branding and personal marketing — and build a presence that pulls attention, not just promotes.",
    summaryAr: "افهم الفرق بين البراند الشخصي والتسويق الشخصي عشان تبني حضور بيشد الانتباه — مش مجرد ترويج.",
    readEn: "5 min read",
    body: [
      { type: "lede",
        en: "Personal marketing sells what you're doing this month. Personal branding sells what people believe about you for years. Both matter — but only one compounds.",
        ar: "التسويق الشخصي بيبيع اللي بتعمله الشهر ده. البراند الشخصي بيبيع اللي الناس مؤمنة بيه عنك على مدار سنين. الاتنين مهمين — بس واحد بس بيراكم." },
      { type: "h2",
        en: "The clearest distinction",
        ar: "أوضح فرق" },
      { type: "p",
        en: "Marketing is what you say. Brand is what stays after you stop saying it. If you turned off every channel tomorrow, marketing would die in 7 days. A real brand would keep referring people to you for years.",
        ar: "التسويق هو اللي بتقوله. البراند هو اللي بيفضل بعد ما تبطّل تقول. لو قفلت كل القنوات بكره، التسويق هيموت في ٧ أيام. لكن البراند الحقيقي هيفضل يجيبلك ناس لسنين." },
      { type: "h2",
        en: "Why most experts pick the wrong one",
        ar: "ليه أغلب الخبراء بيختاروا الغلط" },
      { type: "ul",
        enItems: [
          "Marketing pays this month — branding pays in 18 months.",
          "Marketing is measurable — branding is felt.",
          "Marketing is cheaper to start — branding compounds harder."
        ],
        arItems: [
          "التسويق بيدفع الشهر ده — البراند بيدفع بعد ١٨ شهر.",
          "التسويق ممكن تقيسه — البراند بتحسّه.",
          "التسويق أرخص في البداية — البراند بيراكم أقوى."
        ] },
      { type: "quote",
        en: "Marketing earns the call. Brand earns the referral that already trusts you.",
        ar: "التسويق بيكسب المكالمة. البراند بيكسب الإحالة اللي بتثق فيك من غير ما تتكلم." },
      { type: "h2",
        en: "The right ratio",
        ar: "النسبة الصحيحة" },
      { type: "p",
        en: "Spend 70% of your time on brand — opinions, frameworks, case work, point of view. Spend 30% on marketing — offers, deadlines, direct calls to action. Reverse the ratio and you'll burn out.",
        ar: "اقضي ٧٠٪ من وقتك في البراند — آراء، أطر شغل، Case studies، وجهة نظر. واقضي ٣٠٪ في التسويق — عروض، مواعيد، دعوات مباشرة للتسجيل. لو عكست النسبة، هتحترق." }
    ]
  },

  {
    slug: "personal-brand-core-elements",
    cover: "assets/blogs/04_personal-brand-core-elements.jpg",
    titleEn: "The core elements of a successful personal brand",
    titleAr: "أهم عناصر البراند الشخصي الناجح",
    categoryEn: "Personal Branding · Anatomy",
    categoryAr: "البراند الشخصي · المكوّنات",
    summaryEn: "The essential building blocks of a successful personal brand — from clear message and value, to tone of voice, consistency, and standout traits.",
    summaryAr: "اكتشف العناصر الأساسية للبراند الشخصي الناجح — من الرسالة والقيمة لنبرة الصوت والاتساق وأكتر.",
    readEn: "7 min read",
    body: [
      { type: "lede",
        en: "Six elements separate a brand that people remember from a feed they scroll past. Miss any one and the system leaks.",
        ar: "ست عناصر بتفرق البراند اللي الناس بتفتكره عن الفيد اللي الناس بتعدّي عليه. لو ضاع أي واحد فيهم، النظام بيخسر." },
      { type: "h2",
        en: "1) A message in one sentence",
        ar: "١) رسالة في جملة واحدة" },
      { type: "p",
        en: "If you can't finish \"I help ___ do ___ without ___\" in one breath, the audience can't repeat you. Recommendation cannot survive ambiguity.",
        ar: "لو مش قادر تكمّل \"بساعد ___ يعمل ___ من غير ___\" في نَفَس واحد، الجمهور مش هيقدر يكرّر كلامك. التوصية مش بتعيش وسط الغموض." },
      { type: "h2",
        en: "2) A defendable specialty",
        ar: "٢) تخصص تقدر تدافع عنه" },
      { type: "p",
        en: "Generalists are forgettable by design. Pick the smallest field you can defend, and own it until the audience stops looking elsewhere.",
        ar: "اللي بيشتغل في كل حاجة بيُنسى بطبيعته. اختار أصغر تخصص تقدر تدافع عنه، وامتلكه لحد ما الجمهور يبطّل يدوّر." },
      { type: "h2",
        en: "3) A tone of voice that doesn't translate",
        ar: "٣) نبرة صوت مش ممكن تترجمها لأي حد تاني" },
      { type: "p",
        en: "Your voice should be useless on someone else's account. If your captions could belong to any three competitors, voice is the leak.",
        ar: "صوتك المفروض ميصلحش لحد تاني. لو الكابشن بتاعك ممكن يكون لتلات منافسين، يبقى الصوت هو نقطة الضعف." },
      { type: "h2",
        en: "4) A visual signature anyone could spot",
        ar: "٤) توقيع بصري الكل يقدر يميّزه" },
      { type: "p",
        en: "One colour, one typographic pairing, one motion language. If a friend can scroll past three of your posts at full speed and still identify you, the visual system works.",
        ar: "لون واحد، فونتين متناسقين، لغة حركة واحدة. لو صاحبك يعدّي على ٣ من بوستاتك بسرعة ولسه يعرفك، يبقى النظام البصري شغّال." },
      { type: "h2",
        en: "5) Receipts — visible proof of work",
        ar: "٥) إيصالات — دليل ظاهر على الشغل" },
      { type: "p",
        en: "Opinions need receipts to compound. Show the work — the case studies, the outcomes, the timestamped wins. A brand without receipts is decoration.",
        ar: "الآراء محتاجة إيصالات عشان تتراكم. ورّي الشغل — Case studies، نتائج، إنجازات بتاريخ. براند من غير إيصالات بيبقى زينة." },
      { type: "h2",
        en: "6) A cadence the audience can predict",
        ar: "٦) إيقاع الجمهور يقدر يتنبأ بيه" },
      { type: "p",
        en: "Predictable rhythm is what turns a feed into a habit. Once they expect you on a clock, you've moved from \"creator\" to \"appointment.\"",
        ar: "الإيقاع المتوقع هو اللي بيحوّل الفيد لعادة. لما الجمهور يستنّاك في وقت معين، بتبقى اتحوّلت من \"صانع محتوى\" لـ \"موعد ثابت\"." }
    ]
  },

  {
    slug: "personal-brand-common-mistakes",
    cover: "assets/blogs/05_personal-brand-common-mistakes.jpg",
    titleEn: "Common mistakes that weaken a personal brand",
    titleAr: "أخطاء شائعة تُضعف البراند الشخصي",
    categoryEn: "Personal Branding · Mistakes",
    categoryAr: "البراند الشخصي · أخطاء",
    summaryEn: "The silent mistakes that weaken a personal brand — drifting, copying, selling too early — and how to avoid them.",
    summaryAr: "اعرف الأخطاء الصامتة اللي بتضعّف البراند الشخصي — التذبذب، التقليد، البيع المبكر — وإزاي تتجنّبهم.",
    readEn: "6 min read",
    body: [
      { type: "lede",
        en: "Most brands don't die loud. They drift — quietly — until the audience can no longer describe what you do. These are the silent killers.",
        ar: "أغلب البراندات مش بتموت بصوت عالي. بتتلاشى بهدوء — لحد ما الجمهور ميقدرش يوصف انت بتعمل إيه. دي القتلة الصامتة." },
      { type: "h2",
        en: "Mistake 1 · Pivoting before the position pays",
        ar: "الغلط ١ · تغيير المسار قبل ما الموقع يكافئك" },
      { type: "p",
        en: "Most creators pivot at month 6, just before the curve breaks. The brand needs <strong>boring repetition past the point you're sick of it</strong>. The audience hasn't seen it nearly enough.",
        ar: "أغلب صنّاع المحتوى بيغيّروا المسار في الشهر السادس، قبل ما المنحنى يبدأ يطلع. البراند محتاج <strong>تكرار ممل لحد ما تزهق</strong>. الجمهور لسه مشافش الكلام بشكل كافي." },
      { type: "h2",
        en: "Mistake 2 · Imitating instead of interpreting",
        ar: "الغلط ٢ · التقليد بدل التفسير" },
      { type: "p",
        en: "Copying a competitor's format is fine. Copying their <em>position</em> is fatal. Learn the format; rewrite the position in your own voice.",
        ar: "تقلّد فورمات منافس؟ عادي. تقلّد <em>موقعه</em>؟ كارثة. اتعلم الفورمات، وأعِد كتابة الموقع بصوتك انت." },
      { type: "h2",
        en: "Mistake 3 · Selling on the second post",
        ar: "الغلط ٣ · البيع من البوست التاني" },
      { type: "p",
        en: "Audiences forgive a slow build. They don't forgive a pitch from a stranger. Earn the right to sell — with at least 6 weeks of useful, free work in public.",
        ar: "الجمهور بيسامح البطء. مش بيسامح Pitch من حد مش عارفه. اكسب الحق إنك تبيع — بـ ٦ أسابيع شغل مفيد ومجاني قدّام الناس على الأقل." },
      { type: "h2",
        en: "Mistake 4 · Confusing reach for resonance",
        ar: "الغلط ٤ · الخلط بين الوصول والصدى" },
      { type: "p",
        en: "A million views from the wrong audience is worse than a thousand views from the right one. Optimise for the comment section before the view count.",
        ar: "مليون مشاهدة من جمهور غلط أوحش من ١٠٠٠ مشاهدة من الجمهور الصح. ركّز على التعليقات قبل عدد المشاهدات." },
      { type: "h2",
        en: "Mistake 5 · Hiding behind \"strategy\"",
        ar: "الغلط ٥ · الاختباء وراء \"الاستراتيجية\"" },
      { type: "p",
        en: "Planning is procrastination in a suit. The brand is built in <strong>shipped</strong> work, not deck slides. Publish ugly, refine in public.",
        ar: "التخطيط بدون تنفيذ هو تأجيل في تيشيرت شيك. البراند بيتبني بـ <strong>شغل نازل</strong>، مش سلايدز عرض. انشر حتى لو شكله مش كامل، وحسّن قدّام الناس." }
    ]
  },

  {
    slug: "content-strategy-personal-brand",
    cover: "assets/blogs/06_content-strategy-personal-brand.jpg",
    titleEn: "How to create a content strategy that builds your brand",
    titleAr: "ابني استراتيجية محتوى بتخدم براندك الشخصي",
    categoryEn: "Content Strategy",
    categoryAr: "استراتيجية المحتوى",
    summaryEn: "Build a content strategy that serves your personal brand — from audience definition to content pillars and measurement.",
    summaryAr: "اتعلّم تبني استراتيجية محتوى بتخدم براندك الشخصي — من تحديد الجمهور لأعمدة المحتوى والقياس.",
    readEn: "9 min read",
    body: [
      { type: "lede",
        en: "Most content strategies are content calendars in disguise. A real strategy answers four questions before it picks a single topic.",
        ar: "أغلب \"استراتيجيات المحتوى\" هي جداول محتوى متنكّرة. الاستراتيجية الحقيقية بتجاوب على ٤ أسئلة قبل ما تختار موضوع واحد." },
      { type: "h2",
        en: "Question 1 · Who's the one person you're writing for?",
        ar: "السؤال ١ · مين الشخص الواحد اللي بتكتب له؟" },
      { type: "p",
        en: "Not the segment. The single specific person — name, age, what they tried last week, where they're stuck. If you can't describe the person, the strategy is a guess.",
        ar: "مش الشريحة. الشخص الواحد المحدد — اسمه، سنّه، اللي جرّبه الأسبوع اللي فات، اللي عالق فيه. لو مش قادر توصف الشخص، الاستراتيجية تخمين." },
      { type: "h2",
        en: "Question 2 · What's the transformation?",
        ar: "السؤال ٢ · إيه التحوّل اللي بتعمله؟" },
      { type: "p",
        en: "From state A to state B, in one sentence. Content exists to move people across that gap — anything that doesn't move them is decoration.",
        ar: "من الحالة A للحالة B، في جملة واحدة. المحتوى موجود عشان ينقل الناس عبر الفجوة دي — أي حاجة مش بتحرّكهم، زينة." },
      { type: "h2",
        en: "Question 3 · What are your 3-5 content pillars?",
        ar: "السؤال ٣ · إيه أعمدة المحتوى الـ ٣-٥ بتوعك؟" },
      { type: "p",
        en: "Pillars are the recurring topics you'll cover for the next 12 months. Every post must belong to a pillar. If it doesn't, it's a passenger, not a brand-builder.",
        ar: "الأعمدة هي المواضيع المتكررة اللي هتغطّيها على مدار ١٢ شهر. كل بوست لازم ينتمي لعمود. لو مش بينتمي، يبقى راكب، مش باني." },
      { type: "h2",
        en: "Question 4 · What's your one repeated format?",
        ar: "السؤال ٤ · إيه الفورمات الواحد المتكرر بتاعك؟" },
      { type: "p",
        en: "The format is the container — Tuesday \"Mini Audits,\" Sunday \"5-Slide Frameworks,\" weekly long-form essays. One format, repeated, becomes a habit. Habits become brands.",
        ar: "الفورمات هو الإطار — \"Mini Audits\" كل ثلاثاء، \"5-Slide Frameworks\" كل أحد، مقالات أسبوعية طويلة. فورمات واحد متكرر بيبقى عادة. العادات بتبقى براندات." },
      { type: "quote",
        en: "Content strategy isn't what you'll post. It's what you'll keep posting after no one claps for a month.",
        ar: "استراتيجية المحتوى مش هتنشر إيه. هي إيه اللي هتفضل تنشره بعد شهر مفيش حد عمل لايك." },
      { type: "h2",
        en: "How to measure it",
        ar: "إزاي تقيس النجاح" },
      { type: "ul",
        enItems: [
          "Quarterly, not weekly — single posts lie; quarters tell the truth.",
          "Saves + DMs > Likes — saves measure intent, DMs measure relationship.",
          "Comment quality — three sentences from the right person beats 200 emojis.",
          "Referral language — when prospects describe you in your own words, the strategy is working."
        ],
        arItems: [
          "كل ربع سنة، مش كل أسبوع — البوست الواحد بيكذب، الربع بيقول الحقيقة.",
          "Saves و DMs أهم من اللايكات — الـ Saves بتقيس النية، الـ DMs بتقيس العلاقة.",
          "جودة التعليقات — ٣ جمل من الشخص الصح أحسن من ٢٠٠ إيموجي.",
          "لغة الإحالة — لما العملاء المحتملين يوصفوك بنفس كلامك انت، الاستراتيجية شغّالة."
        ] }
    ]
  },

  {
    slug: "turn-expertise-into-brand-that-sells",
    cover: "assets/blogs/07_turn-expertise-into-brand-that-sells.jpg",
    titleEn: "How to turn your expertise into a personal brand that sells",
    titleAr: "حوّل خبرتك لبراند شخصي بيبيع",
    categoryEn: "Conversion · Authority",
    categoryAr: "تحويل · سلطة",
    summaryEn: "Turn your expertise into a personal brand that communicates value clearly and attracts the right clients — without pressure selling.",
    summaryAr: "حوّل خبرتك لبراند شخصي بيوصّل قيمتك بوضوح وبيجذب العملاء المناسبين — من غير ضغط بيع.",
    readEn: "7 min read",
    body: [
      { type: "lede",
        en: "Expertise doesn't sell. <strong>Translated</strong> expertise does. The translation gap is where most experts lose 80% of the money their skills should make.",
        ar: "الخبرة لوحدها مش بتبيع. <strong>الخبرة المترجمة</strong> هي اللي بتبيع. فجوة الترجمة هي المكان اللي أغلب الخبراء بيخسروا فيه ٨٠٪ من الفلوس اللي مهاراتهم المفروض تجيبها." },
      { type: "h2",
        en: "Translation Layer 1 · Outcome, not service",
        ar: "طبقة الترجمة ١ · النتيجة، مش الخدمة" },
      { type: "p",
        en: "\"I run paid ads\" is a service. \"I fill specialist doctor clinics in 45 days\" is an outcome. Outcomes book calls. Services compete on price.",
        ar: "\"بشتغل إعلانات\" دي خدمة. \"بملا عيادات الأخصائيين في ٤٥ يوم\" دي نتيجة. النتيجة بتجيب مكالمات. الخدمة بتنافس على السعر." },
      { type: "h2",
        en: "Translation Layer 2 · Mechanism, not magic",
        ar: "طبقة الترجمة ٢ · الميكانيزم، مش السحر" },
      { type: "p",
        en: "Buyers don't trust outcomes without a mechanism. Name your system. Diagram it. Make the invisible visible. \"How I do it\" beats \"trust me.\"",
        ar: "المشتري مش بيثق في النتيجة من غير ميكانيزم. سمّي نظامك. ارسمه. خلّي اللي مخفي يبقى ظاهر. \"إزاي بعملها\" أقوى من \"وثق فيّا\"." },
      { type: "h2",
        en: "Translation Layer 3 · Receipts, repeated",
        ar: "طبقة الترجمة ٣ · إيصالات، متكررة" },
      { type: "p",
        en: "One case study converts. Five case studies <em>compound</em>. Build the receipts library and reference it casually — never defensively.",
        ar: "Case study واحدة بتحوّل. ٥ Case studies <em>بتراكم</em>. ابنِي مكتبة الإيصالات بتاعتك واستخدمها بشكل عابر — مش دفاعي." },
      { type: "h2",
        en: "Translation Layer 4 · Public diagnosis",
        ar: "طبقة الترجمة ٤ · تشخيص علني" },
      { type: "p",
        en: "The fastest authority shortcut: diagnose other people's work, publicly. A free, sharp diagnosis is worth more than five sales DMs. Diagnose the work in your industry that everyone else is too polite to address.",
        ar: "أسرع طريق للسلطة المعرفية: شخّص شغل ناس تانية، علناً. تشخيص مجاني وحاد قيمته أكتر من ٥ رسايل بيع. شخّص الشغل في مجالك اللي الكل مؤدّب أوي يتكلم فيه." },
      { type: "h2",
        en: "Translation Layer 5 · A clear ladder",
        ar: "طبقة الترجمة ٥ · سلّم واضح" },
      { type: "p",
        en: "Free content → low-ticket product → consultation → main offer. If the audience can't see the ladder, they freeze at the bottom. Make every rung obvious.",
        ar: "محتوى مجاني → منتج رخيص → استشارة → العرض الأساسي. لو الجمهور مش شايف السلّم، هيتجمّد في الأسفل. خلّي كل درجة واضحة." }
    ]
  },

  {
    slug: "build-trust-through-personal-branding",
    cover: "assets/blogs/08_build-trust-through-personal-branding.jpg",
    titleEn: "How to build trust through personal branding",
    titleAr: "إزاي تبني الثقة من خلال البراند الشخصي",
    categoryEn: "Trust · Growth",
    categoryAr: "ثقة · نمو",
    summaryEn: "Trust compounds when you do these things, every week, for a long time. A real protocol — not a hack.",
    summaryAr: "الثقة بتتراكم لما تعمل الحاجات دي، كل أسبوع، لفترة طويلة. بروتوكول حقيقي — مش حيلة.",
    readEn: "6 min read",
    body: [
      { type: "lede",
        en: "Trust is the slowest brand metric to move and the most expensive to lose. There are no growth hacks for trust — only protocols, repeated.",
        ar: "الثقة أبطأ مؤشر في البراند بيتحرّك، وأغلى حاجة لما تضيع. مفيش Growth hacks للثقة — في بس بروتوكولات، بتتكرّر." },
      { type: "h2",
        en: "Protocol 1 · Predictability",
        ar: "البروتوكول ١ · القابلية للتنبؤ" },
      { type: "p",
        en: "Trust starts at predictability. If your audience can guess when you'll post, what you'll say, and what you'll never say — you're 60% there.",
        ar: "الثقة بتبدأ من القابلية للتنبؤ. لو جمهورك يقدر يحزر هتنشر إمتى، هتقول إيه، ومش هتقول إيه — انت قطعت ٦٠٪ من الطريق." },
      { type: "h2",
        en: "Protocol 2 · The cost of public opinion",
        ar: "البروتوكول ٢ · ثمن الرأي العلني" },
      { type: "p",
        en: "Take public positions that have a cost — a competitor lost, an opportunity refused, a popular practice rejected. Costly positions are the ones audiences remember as <strong>integrity</strong>.",
        ar: "اتخذ مواقف علنية ليها ثمن — منافس خسرته، فرصة رفضتها، ممارسة شائعة رفضتها. المواقف اللي ليها ثمن هي اللي الجمهور بيفتكرها كـ <strong>نزاهة</strong>." },
      { type: "h2",
        en: "Protocol 3 · Receipts before claims",
        ar: "البروتوكول ٣ · إيصالات قبل الادعاءات" },
      { type: "p",
        en: "Show the work before you describe it. A 12-second video of a result beats a 600-word caption claiming it.",
        ar: "ورّي الشغل قبل ما توصفه. فيديو ١٢ ثانية بنتيجة، أقوى من ٦٠٠ كلمة في كابشن بتدّعي النتيجة." },
      { type: "h2",
        en: "Protocol 4 · Slow scaling",
        ar: "البروتوكول ٤ · توسّع بطيء" },
      { type: "p",
        en: "Brands that scale too fast leak trust on the way up. Audience growth without proof of capacity reads as performance. Grow slow enough to keep the receipts up to date.",
        ar: "البراند اللي بيكبر بسرعة بيخسر ثقة وهو بيكبر. لو جمهورك بيكبر من غير دليل على القدرة، الناس بتحسّ إنه أداء. اتوسّع ببطء كفاية إن الإيصالات تفضل محدّثة." }
    ]
  },

  {
    slug: "when-need-agency-personal-brand",
    cover: "assets/blogs/09_when-need-agency-personal-brand.jpg",
    titleEn: "When do you need an agency to build your personal brand?",
    titleAr: "إمتى تحتاج وكالة عشان تبني براندك الشخصي؟",
    categoryEn: "Decisions · DIY vs. Agency",
    categoryAr: "قرارات · DIY أم وكالة",
    summaryEn: "Know when to build your personal brand yourself — and when an agency saves time, accelerates positioning, and protects your reputation.",
    summaryAr: "اعرف إمتى تبني براندك الشخصي بنفسك — وإمتى الوكالة هتوفّرلك الوقت، تسرّع تموضعك، وتحمي سمعتك.",
    readEn: "6 min read",
    body: [
      { type: "lede",
        en: "Hiring an agency too early wastes money. Hiring one too late wastes the curve. Here's how to know where you are.",
        ar: "تستأجر وكالة بدري بتضيع فلوس. تستأجر متأخر بتضيع المنحنى. ده إزاي تعرف انت فين دلوقتي." },
      { type: "h2",
        en: "DIY the first 6 months",
        ar: "اعمل بنفسك أول ٦ شهور" },
      { type: "p",
        en: "Nobody outsources discovery. The first 6 months are where you find your voice, test angles, and live in the comment section. No agency can do this for you — they can only systematise it after.",
        ar: "محدش بيخرج مرحلة الاكتشاف لحد. أول ٦ شهور هي اللي بتلاقي فيها صوتك، تجرّب زوايا، وتسكن في التعليقات. مفيش وكالة تقدر تعمل ده بدالك — هما بس بيقدروا ينظّموه بعد كده." },
      { type: "h2",
        en: "Hire an agency when 3 things are true",
        ar: "استأجر وكالة لما ٣ حاجات يبقوا صح" },
      { type: "ol",
        enItems: [
          "You know your position. You can describe what you do in one sentence without thinking.",
          "Your time costs more than the agency's fee. Every hour you spend editing is an hour not earning.",
          "You have receipts. There's enough proof of work that an agency can amplify, not invent."
        ],
        arItems: [
          "انت عارف موقعك. تقدر توصف اللي بتعمله في جملة واحدة من غير ما تفكر.",
          "وقتك بيكلّفك أكتر من سعر الوكالة. كل ساعة في المونتاج، ساعة مش بتكسبها.",
          "عندك إيصالات. في دليل شغل كافي إن الوكالة تكبّره، مش تخترعه."
        ] },
      { type: "h2",
        en: "What a good agency actually does",
        ar: "الوكالة الكويسة بتعمل فعلاً إيه" },
      { type: "ul",
        enItems: [
          "Turns scattered work into a system you can scale without burning out.",
          "Buys back your most expensive hours — editing, design, scheduling, scripting.",
          "Protects the position by saying \"no\" to opportunities that dilute it.",
          "Documents the wins so your next conversation starts at \"impressed,\" not \"introduce yourself.\""
        ],
        arItems: [
          "بتحوّل شغلك المبعثر لنظام تقدر تكبّره من غير ما تحترق.",
          "بتفضّيلك أغلى ساعاتك — مونتاج، تصميم، جدولة، كتابة سكريبت.",
          "بتحمي موقعك بإنها تقول \"لأ\" للفرص اللي بتميّعه.",
          "بتوثّق الإنجازات عشان أول محادثة جاية تبدأ من \"معجب\"، مش من \"عرّف نفسك\"."
        ] }
    ]
  },

  {
    slug: "measure-success-of-personal-brand",
    cover: "assets/blogs/10_measure-success-of-personal-brand.jpg",
    titleEn: "How to measure the success of your personal brand",
    titleAr: "إزاي تقيس نجاح براندك الشخصي",
    categoryEn: "Measurement",
    categoryAr: "القياس",
    summaryEn: "Beyond vanity metrics — the indicators that prove your personal brand is actually working, compounding, and converting.",
    summaryAr: "أبعد من مقاييس الغرور — المؤشرات اللي بتثبت إن براندك الشخصي شغّال، بيراكم، وبيحوّل.",
    readEn: "7 min read",
    body: [
      { type: "lede",
        en: "Likes are the loudest, weakest signal a brand can send. Real measurement reads three quieter signals — and ignores everything else.",
        ar: "اللايكات هي أعلى وأضعف إشارة ممكن يرسلها براند. القياس الحقيقي بيقرأ ٣ إشارات أهدى — ومتجاهل أي حاجة تانية." },
      { type: "h2",
        en: "Signal 1 · Inbound quality",
        ar: "الإشارة ١ · جودة الـ Inbound" },
      { type: "p",
        en: "Don't count DMs. Read them. Are the people reaching out the people you wanted to reach? If yes, the brand is targeting correctly. If no, the targeting is the leak — not the volume.",
        ar: "ماتعدّش الرسايل. اقراها. الناس اللي بتيجيلك، هي اللي كنت عايز توصلهم؟ لو آه، البراند بيستهدف صح. لو لأ، الاستهداف هو المشكلة — مش العدد." },
      { type: "h2",
        en: "Signal 2 · Pricing power",
        ar: "الإشارة ٢ · القدرة على التسعير" },
      { type: "p",
        en: "A real brand lets you raise prices without losing demand. If you tested a 30% price increase and didn't lose 30% of clients, your brand is doing its job. If you can't even consider the increase, the brand isn't there yet.",
        ar: "البراند الحقيقي بيخلّيك ترفع السعر من غير ما تخسر الطلب. لو رفعت السعر ٣٠٪ ومخسرتش ٣٠٪ من العملاء، البراند بيشتغل. لو مش قادر تفكّر تزوّد أصلاً، البراند لسه مش وصل." },
      { type: "h2",
        en: "Signal 3 · Referral language",
        ar: "الإشارة ٣ · لغة الإحالة" },
      { type: "p",
        en: "Listen to how new prospects describe you on the discovery call. If they're repeating <em>your</em> words back to you — your positioning has compounded. If they're describing you in their own words — the position hasn't landed yet.",
        ar: "اسمع العميل الجديد بيوصفك إزاي في أول مكالمة. لو بيرجّعلك كلامك انت — يبقى التموضع راكم. لو بيوصفك بكلامه هو — يبقى الموقع لسه مش وصل." },
      { type: "h2",
        en: "What to ignore",
        ar: "اللي تتجاهله" },
      { type: "ul",
        enItems: [
          "Follower count without intent.",
          "Single-post performance — quarters tell the truth.",
          "Vanity metrics from platforms that don't drive your revenue.",
          "Compliments from peers — they're not your buyers."
        ],
        arItems: [
          "عدد المتابعين من غير نية شراء.",
          "أداء بوست واحد — كل ربع سنة بيقول الحقيقة.",
          "مقاييس غرور من منصّات مش بتجيبلك دخل.",
          "مديح الزملاء — هم مش مشترييك."
        ] },
      { type: "quote",
        en: "If your brand is working, your inbound gets sharper, your prices rise, and your audience hands you your own words.",
        ar: "لو براندك شغّال، الـ Inbound بيبقى أوضح، الأسعار بترتفع، والجمهور بيرجّعلك كلامك انت." }
    ]
  }
];

// Build a quick lookup
window.BLOG_POSTS_BY_SLUG = {};
window.BLOG_POSTS.forEach(function (p) { window.BLOG_POSTS_BY_SLUG[p.slug] = p; });
